---
# Tasks for the base CDF installation

- name: Install Java JDK 1.8
  yum:
    name: java-1.8.0-openjdk-devel
    state: present
  tags: [setup]

- name: create CDF system group
  group:
    name: cdf
    state: present
  tags: [setup]

- name: create CFM system group
  group:
    name: cfm
    state: present
  tags: [setup]

- name: create CEM system group
  group:
    name: "{{ cem_group }}"
    state: present
  tags: [setup]

- name: create nifi-registry system account
  user:
    name: "{{ nifi_registry_run_as }}"
    groups: cdf
    append: yes
    system: yes
    state: present
  when: nifi_registry_run_as != "root"
  tags: [setup]

- name: create nifi-toolkit system account
  user:
    name: nifi-toolkit
    groups: cdf
    append: yes
    system: yes
    state: present
  tags: [setup]

- name: create minificpp system account
  user:
    name: minificpp
    groups: cem
    append: yes
    system: yes
    state: present
  tags: [setup]

- name: Create the CDF base directory
  file:
    path: /usr/cdf
    owner: root
    group: cdf
    state: directory
    mode: 0775

- name: Create the base CEM directory
  file:
    path: /usr/cdf/cem
    owner: root
    group: cem
    state: directory
    mode: 0775

- name: Create CDF Common directory
  file:
    path: /usr/cdf/common
    owner: root
    group: cdf
    state: directory
    mode: 0775

- name: Create CFM directory
  file:
    path: /usr/cdf/cfm
    owner: root
    group: cfm
    state: directory
    mode: 0775

- name: Create NiFi Registry Directory
  file:
    path: /usr/cdf/common/nifi-registry
    owner: nifi-registry
    group: cdf
    state: directory
    mode: 0775

- name: Create NiFi Toolkit Directory
  file:
    path: /usr/cdf/common/nifi-toolkit
    owner: nifi-toolkit
    group: cdf
    state: directory
    mode: 0775

- name: Create CEM current dir
  file:
    path: /usr/cdf/cem/current
    owner: root
    group: cem
    state: directory
    mode: 0775